# Generated by Django 4.2.3 on 2026-03-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="force_password_change",
            field=models.BooleanField(
                default=False, help_text="User must change password on next login"
            ),
        ),
    ]
