# Generated by Django 4.2.3 on 2026-02-25 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merchandise", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        help_text="Current balance of this product for this sales user",
                    ),
                ),
                (
                    "is_unlimited",
                    models.BooleanField(
                        default=False, help_text="If True, bypasses all checkout limits"
                    ),
                ),
                (
                    "max_per_checkout",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum quantity per single checkout. Null = unlimited",
                        null=True,
                    ),
                ),
                (
                    "max_daily",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum total checkout quantity per day. Null = unlimited",
                        null=True,
                    ),
                ),
                (
                    "daily_used",
                    models.IntegerField(
                        default=0,
                        help_text="Total quantity checked out today (lazy reset)",
                    ),
                ),
                (
                    "last_checkout_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of last checkout, used for daily reset",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchandise",
                    models.ForeignKey(
                        help_text="Merchandise allocated to this sales user",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_inventories",
                        to="merchandise.merchandise",
                    ),
                ),
                (
                    "sales_user",
                    models.ForeignKey(
                        help_text="Sales user who owns this inventory allocation",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_inventories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Inventory",
                "verbose_name_plural": "Sales Inventories",
                "db_table": "sales_inventory",
                "ordering": ["sales_user__username", "merchandise__name"],
                "unique_together": {("sales_user", "merchandise")},
            },
        ),
        migrations.CreateModel(
            name="SalesInventoryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sales_user_name",
                    models.CharField(
                        help_text="Snapshot of sales user name", max_length=200
                    ),
                ),
                (
                    "merchandise_name",
                    models.CharField(
                        help_text="Snapshot of merchandise name", max_length=200
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ALLOCATE", "Alokasi (Admin)"),
                            ("REDUCE", "Pengurangan (Admin)"),
                            ("CHECKOUT", "Checkout (Sales)"),
                        ],
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "adjustment",
                    models.IntegerField(
                        help_text="Quantity change: positive for allocate, negative for reduce/checkout"
                    ),
                ),
                (
                    "qty_before",
                    models.IntegerField(help_text="Quantity before this action"),
                ),
                (
                    "qty_after",
                    models.IntegerField(help_text="Quantity after this action"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes for this action"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this action was performed"
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed this action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_inventory",
                    models.ForeignKey(
                        help_text="Related sales inventory record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="inventory.salesinventory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Inventory History",
                "verbose_name_plural": "Sales Inventory Histories",
                "db_table": "sales_inventory_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
