# Generated by Django 4.2.3 on 2026-03-04 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nama tool/produk untuk sales",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Deskripsi tool"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Foto tool",
                        null=True,
                        upload_to="sales_tools/%Y/%m/",
                    ),
                ),
                ("stock", models.IntegerField(default=0, help_text="Stock tersedia")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Tool aktif/non-aktif"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Admin yang membuat tool ini",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tools",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Tool",
                "verbose_name_plural": "Sales Tools",
                "db_table": "sales_tools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ToolCheckout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(help_text="Jumlah yang di-checkout")),
                ("notes", models.TextField(blank=True, help_text="Catatan dari sales")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        help_text="Status checkout",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Waktu checkout"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="Waktu di-review", null=True
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Catatan dari admin"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin yang review",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_checkouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_user",
                    models.ForeignKey(
                        help_text="Sales user yang checkout",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tool_checkouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        help_text="Tool yang di-checkout",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkouts",
                        to="inventory.salestool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool Checkout",
                "verbose_name_plural": "Tool Checkouts",
                "db_table": "tool_checkouts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="tool_checko_status_55cdec_idx",
                    ),
                    models.Index(
                        fields=["sales_user", "-created_at"],
                        name="tool_checko_sales_u_be3db5_idx",
                    ),
                ],
            },
        ),
    ]
