# Generated by Django 4.2.3 on 2026-03-05 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_salestool_toolcheckout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama kategori tools', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Deskripsi kategori')),
                ('is_active', models.BooleanField(default=True, help_text='Kategori aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tool Category',
                'verbose_name_plural': 'Tool Categories',
                'db_table': 'tool_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='salestool',
            name='is_unlimited',
            field=models.BooleanField(default=False, help_text='Tool unlimited — bisa digunakan berkali-kali tanpa mengurangi stok (contoh: tenda, spanduk)'),
        ),
        migrations.AlterField(
            model_name='salestool',
            name='stock',
            field=models.IntegerField(default=0, help_text='Stock tersedia (diabaikan jika unlimited)'),
        ),
        migrations.AddField(
            model_name='salestool',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Kategori tool (opsional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='inventory.toolcategory'),
        ),
    ]
