# Generated by Django 4.2.3 on 2026-02-05 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (must be unique)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('is_active', models.BooleanField(default=True, help_text='Active status (soft delete)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Merchandise name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Merchandise description')),
                ('stock', models.IntegerField(default=0, help_text='Current stock quantity')),
                ('image', models.ImageField(blank=True, help_text='Merchandise image (max 2MB, JPG/PNG)', null=True, upload_to='merchandise/%Y/%m/')),
                ('is_active', models.BooleanField(default=True, help_text='Active status (soft delete)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category for this merchandise', on_delete=django.db.models.deletion.PROTECT, to='merchandise.category')),
                ('created_by', models.ForeignKey(help_text='User who created this merchandise', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_merchandise', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchandise',
                'verbose_name_plural': 'Merchandise',
                'db_table': 'merchandise',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment', models.IntegerField(help_text='Stock adjustment amount (positive or negative)')),
                ('stock_before', models.IntegerField(help_text='Stock quantity before adjustment')),
                ('stock_after', models.IntegerField(help_text='Stock quantity after adjustment')),
                ('reason', models.CharField(help_text='Reason for adjustment', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(help_text='User who made the adjustment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('merchandise', models.ForeignKey(help_text='Related merchandise', on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='merchandise.merchandise')),
            ],
            options={
                'verbose_name': 'Stock History',
                'verbose_name_plural': 'Stock History',
                'db_table': 'stock_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
