# Generated by Django 4.2.3 on 2026-03-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='is_unlimited',
            field=models.BooleanField(default=False, help_text='Stok unlimited — bisa digunakan berkali-kali tanpa mengurangi stok (contoh: tenda, spanduk)'),
        ),
    ]
