# Generated by Django 4.2.3 on 2026-02-05 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchandise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Auto-generated order number (ORD-YYYYMMDD-XXXX)', max_length=50, unique=True)),
                ('customer_name', models.CharField(help_text='Customer full name', max_length=200)),
                ('customer_phone', models.CharField(help_text='Customer WhatsApp number', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Order creation timestamp')),
                ('sales_user', models.ForeignKey(help_text='Sales user who created this order', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchandise_name', models.CharField(help_text='Merchandise name snapshot', max_length=200)),
                ('quantity', models.IntegerField(help_text='Quantity ordered')),
                ('merchandise', models.ForeignKey(help_text='Merchandise item', on_delete=django.db.models.deletion.PROTECT, to='merchandise.merchandise')),
                ('order', models.ForeignKey(help_text='Related order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items',
                'ordering': ['id'],
            },
        ),
    ]
